@startuml
'https://plantuml.com/class-diagram

class Jugador {
    +recibirAtaque(Enemigo: enemigo): void
    +sumarCreditos(int : cantidad): void
    +atacar(): void
    +VidaObtener() : int
}

class Creditos {
    -valor: int
    +modificar(int : Valor): void
}

class Nombre {
    -nombre : String
    +Nombre(String : string)
}

class Vida {
    -valor: int
    +modificar(int : Valor): void
    +cantidad() : int
}

class Score {
    +sumar(Enemigo: enemigo): void
}

abstract class Defensa {
    +Defensa(Parcela : lugar)
    +atacar(Enemigo : enemigo)
    +construir()
}

class sistemaDeAtaque{
    -daño: int
    -rango: int
    +SistemaDeAtaque(int daño, int rango)
    +atacar()
}

class turnosNecesarios{
    -turnosFaltantes: int
    +TurnosNecesarios(int turnos)
    +estaOperativa(): Bool
    +construir()
}

class TorreBlanca{
    +atacar(Enemigo : enemigo): void
}

class TorrePlateada{
    +atacar(Enemigo: enemigo): void
}


interface Parcela {
    +ubicar(Defensa : defensa): void
}

class InterfazGrafica {}

class Tierra {
    +ubicar(Defensa : defensa): void
}

class Rocoso {
    +ubicar(Defensa : defensa): void
}

abstract class Pasarela {
    +ubicar(Defensa : defensa): void
}

class Meta {}
class Largada {}

abstract class Enemigo {
    +recibirAtaque(Defensa : defensa): void
    +destruirse(): void
    +atacar(Jugador : jugador): void
}

class Hormiga {
    +destruirse(): void
    +atacar(Jugador : jugador): void
}

class Araña {
    +destruirse(): void
    +atacar(Jugador : jugador): void
}

class Daño {
    +atacar(Jugador : jugador): void
}

class Velocidad {
    +moverse(): void
}

Jugador  *-->  Creditos
Jugador  *-->  Nombre
Jugador  *-->  Vida
Jugador  *--> "0..*" Defensa
Score  o-->  Jugador

Defensa <|--- TorreBlanca
Defensa <|--- TorrePlateada
Defensa <..> Enemigo
Defensa *--> sistemaDeAtaque
Defensa *--> turnosNecesarios

Parcela o--> Defensa
Parcela "1..*" <--*  InterfazGrafica
Parcela <|.. Tierra
Parcela <|.. Rocoso
Parcela <|.. Pasarela

Pasarela <|-- Meta
Pasarela <|-- Largada

Enemigo <|-- Hormiga
Enemigo <|-- Araña
Enemigo *--> Daño
Enemigo *--> Velocidad
Enemigo "0..*" <--  Score
Enemigo ..> Jugador
Enemigo *--> Vida
Enemigo <--o Parcela




@enduml