@startuml
'https://plantuml.com/class-diagram

interface Enemigos
interface Defensa
class Hormiga
class Araña
abstract class Torre
abstract class Bicho{
Velocidad
Daño
Energia
Creditos
}
class Blanca
class Plateada
class Jugador

Enemigos : Atacar(J: Jugador)
Enemigos : RecibirDaño(D: Defensa)

Bicho : Atacar(J: Jugador)
Bicho : RecibirDaño(D: Defensa)

Enemigos <|.. Bicho
Bicho <|-- Hormiga
Bicho <|-- Araña

Defensa <|.. Torre
Torre <|-- Blanca
Torre <|-- Plateada



@enduml