@startuml
'https://plantuml.com/class-diagram

class Jugador {
    +recibirAtaque(unidad: Unidad): void
    +sumarCreditos(int cantidad): void
    +atacar(): void
}

class Creditos {
    -valor: int
    +modificar(int Valor): void
}

class Nombre {
    +Nombre(String string)
}

class Vida {
    -valor: int
    +modificar(int Valor): void
}

class Score {
    +sumar(Unidad unidad): void
}

abstract class Unidad {
    +recibirAtaque(Defensa defensa): void
    +destruirse(): void
    +atacar(Jugador jugador): void
}

Unidad ..> Jugador
Jugador "1" *-- "1" Creditos
Jugador "1" *-- "1" Nombre
Jugador "1" *-- "1" Vida
Score "1" o-- "1" Jugador

@enduml